FROM centos:centos7.2.1511

ENV PATH /usr/local/python3/bin:$PATH

RUN yum install -y zlib zlib-devel readline-devel sqlite-devel bzip2-devel openssl-devel gdbm-devel libdbi-devel ncurses-libs kernel-devel libxslt-devel libffi-devel python-devel zlib-devel openldap-devel sshpass gcc wget make \
    && cd /usr/local/src \
    && wget https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tgz \
    && tar -xzvf Python-3.6.6.tgz \
    && cd /usr/local/src/Python-3.6.6 \
    && ./configure --prefix=/usr/local/python3 \
    && make all \
    && make install \
    && make clean \
    && make distclean \
    && cd / \
    && rm -rf /usr/local/src/Python* \
    && yum clean all \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3 \
    && ln -s /usr/local/python3/bin/python3 /usr/bin/python3 \
    && ln -s /usr/local/python3/bin/easy_install-3.6 /usr/bin/easy_install \
    && pip3 install --upgrade pip setuptools \
    && python3 --version \
    && pip3 --version

CMD ["python3"]